### ISSUE TITLE
Weekly Report 2023-04-24

### ISSUE THREAD

**Issue by nchithan** [SCCapstone/Delta#252]

**Comment by nchithan** [comment]
Recorded final video and submitted Thesis Paper

**Comment by vancevince** [comment]
complete #507

**Comment by lxaw** [comment]
Recording of video, fixing small UI issues. Finalizing 492.

**Comment by Cmarlowe132** [comment]
Recording of final video, submitted thesis paper, group member review forms, final testing of app

**Comment by j-blake-s** [comment]
Recorded final video, reviews, and final testing
