### ISSUE TITLE
OS gone

### ISSUE THREAD

**Issue by vancevince** [SCCapstone/Delta#508]
Not really sure what happened but it looks like Ubuntu got wiped from laptop. I'll try to reinstall it but until then the best way to reach me is by email or text. I'll check back periodically for updates.

Also, don't think I'm making tonight's meeting.

**Comment by vancevince** [comment]
@lxaw see the above issue

**Comment by lxaw** [comment]
@vancevince Understood; do you still have that other laptop? I mean tbh I am not sure what to do about this one my friend but we should be fine. Not sure if you can see this message then either.

**Comment by vancevince** [comment]
@lxaw I returned it to my brother (it was his) but I think that I can just reinstall Ubuntu with a thumbdrive. I just need to download the stuff again and then do the boot.

If you need to reach me do it here or through email, I'll make sure to check them periodically.
